import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

# Load the dataset
anime_df = pd.read_csv("anime.csv")

# Fill missing values
anime_df['genre'] = anime_df['genre'].fillna('')
anime_df['type'] = anime_df['type'].fillna('')
anime_df['rating'] = anime_df['rating'].fillna(anime_df['rating'].mean())

# Combine text features
anime_df['combined_features'] = anime_df['genre'] + ' ' + anime_df['type'] + ' ' + anime_df['rating'].astype(str)

# Initialize TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the combined features
tfidf_matrix = tfidf_vectorizer.fit_transform(anime_df['combined_features'])

def recommend_anime(anime_title, num_recommendations, tfidf_matrix=tfidf_matrix):
    # Find the index of the given anime title
    anime_index = anime_df[anime_df['name'] == anime_title].index[0]

    # Calculate cosine similarity between the given anime and all other anime
    cosine_similarities = linear_kernel(tfidf_matrix[anime_index], tfidf_matrix).flatten()

    # Get top similar anime indices based on the user-defined number
    similar_anime_indices = cosine_similarities.argsort()[-(num_recommendations + 1):-1][::-1]

    # Get similar anime titles
    similar_anime_titles = anime_df.iloc[similar_anime_indices]['name'].values

    return similar_anime_titles

# Streamlit UI
st.title("Anime Recommendation System")

# Apply custom CSS to change the color of the text input
st.markdown(
    """
    <style>
    .st-ef {
        color: black !important;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# List of allowed anime titles
allowed_titles = ['Kimi no Na wa.',
 'Fullmetal Alchemist: Brotherhood',
 'Gintama°',
 'Steins;Gate',
 'Gintama&#039;',
 'Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou',
 'Hunter x Hunter (2011)',
 'Ginga Eiyuu Densetsu',
 'Gintama Movie: Kanketsu-hen - Yorozuya yo Eien Nare',
 'Gintama&#039;: Enchousen',
 'Clannad: After Story',
 'Koe no Katachi',
 'Gintama',
 'Code Geass: Hangyaku no Lelouch R2',
 'Haikyuu!! Second Season',
 'Sen to Chihiro no Kamikakushi',
 'Shigatsu wa Kimi no Uso',
 'Mushishi Zoku Shou 2nd Season',
 'Ookami Kodomo no Ame to Yuki',
 'Code Geass: Hangyaku no Lelouch',
 'Hajime no Ippo',
 'Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen',
 'Cowboy Bebop',
 'One Punch Man',
 'Mononoke Hime',
 'Suzumiya Haruhi no Shoushitsu',
 'Monogatari Series: Second Season',
 'Mushishi Zoku Shou',
 'Mushishi',
 'Tengen Toppa Gurren Lagann',
 'Great Teacher Onizuka',
 'Natsume Yuujinchou Go',
 'Hajime no Ippo: New Challenger',
 'Mushishi Zoku Shou: Suzu no Shizuku',
 'Natsume Yuujinchou Shi',
 'Howl no Ugoku Shiro',
 'Fate/Zero 2nd Season',
 'Kizumonogatari II: Nekketsu-hen',
 'Monster',
 'Bakuman. 3rd Season',
 'Death Note',
 'Gintama°: Aizome Kaori-hen',
 'Ansatsu Kyoushitsu (TV) 2nd Season',
 'Haikyuu!!',
 'Hajime no Ippo: Rising',
 'Kara no Kyoukai 5: Mujun Rasen',
 'Natsume Yuujinchou San',
 'Ping Pong The Animation',
 'Mushishi Special: Hihamukage',
 'Boku dake ga Inai Machi',
 'Yojouhan Shinwa Taikei',
 'Aria The Origination',
 'Kamisama Hajimemashita: Kako-hen',
 'Rainbow: Nisha Rokubou no Shichinin',
 'Re:Zero kara Hajimeru Isekai Seikatsu',
 'Tengen Toppa Gurren Lagann Movie: Lagann-hen',
 'Zoku Natsume Yuujinchou',
 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.',
 'Kuroko no Basket 3rd Season',
 'Steins;Gate Movie: Fuka Ryouiki no Déjà vu',
 'Hotarubi no Mori e',
 'Shokugeki no Souma',
 'Yuri!!! on Ice',
 'Gintama: Yorinuki Gintama-san on Theater 2D',
 'JoJo no Kimyou na Bouken: Stardust Crusaders 2nd Season',
 'Gintama Movie: Shinyaku Benizakura-hen',
 'Hellsing Ultimate',
 'Kiseijuu: Sei no Kakuritsu',
 'Shouwa Genroku Rakugo Shinjuu',
 'Uchuu Kyoudai',
 'Bakemono no Ko',
 'Hotaru no Haka',
 'Kuroko no Basket 2nd Season',
 'Major S5',
 'One Piece',
 'Ghost in the Shell: Stand Alone Complex 2nd GIG',
 'JoJo no Kimyou na Bouken: Diamond wa Kudakenai',
 'Kara no Kyoukai 7: Satsujin Kousatsu (Kou)',
 'Kingdom 2nd Season',
 'Slam Dunk',
 'Usagi Drop',
 'Girls und Panzer der Film',
 'Mob Psycho 100',
 'Nana',
 'Baccano!',
 'Mushishi Zoku Shou: Odoro no Michi',
 'Shingeki no Kyojin',
 'Bakuman. 2nd Season',
 'Cross Game',
 'Doukyuusei (Movie)',
 'Evangelion: 2.0 You Can (Not) Advance',
 'Shinsekai yori',
 'Uchuu Senkan Yamato 2199',
 'Chihayafuru 2',
 'Fate/Zero',
 'JoJo no Kimyou na Bouken (TV)',
 'Mahou Shoujo Madoka★Magica',
 'Nichijou',
 'Psycho-Pass',
 'Barakamon',
 'Diamond no Ace: Second Season',
 'Magi: The Kingdom of Magic',
 'Mahou Shoujo Madoka★Magica Movie 3: Hangyaku no Monogatari',
 'Major: World Series',
 'Samurai Champloo',
 'Shokugeki no Souma: Ni no Sara',
 'Katanagatari',
 'Mahou Shoujo Madoka★Magica Movie 2: Eien no Monogatari',
 'Major S6',
 'Mononoke',
 'Shirobako',
 'Ashita no Joe 2',
 'Hunter x Hunter',
 'Noragami Aragoto',
 'Sakamichi no Apollon',
 'Tonari no Totoro',
 'Ghost in the Shell: Stand Alone Complex',
 'Kaze no Tani no Nausicaä',
 'No Game No Life',
 'Romeo no Aoi Sora',
 'Yuu☆Yuu☆Hakusho',
 'Kino no Tabi: The Beautiful World',
 'Kuroko no Basket',
 'Nodame Cantabile',
 'Ookami to Koushinryou II',
 'Shingeki no Kyojin: Kuinaki Sentaku',
 'Steins;Gate: Oukoubakko no Poriomania',
 'Fate/stay night: Unlimited Blade Works 2nd Season',
 'Kemono no Souja Erin',
 'Kizumonogatari I: Tekketsu-hen',
 'Neon Genesis Evangelion: The End of Evangelion',
 'Toradora!',
 'Toki wo Kakeru Shoujo',
 'Tsubasa: Tokyo Revelations',
 'Owarimonogatari',
 'Rurouni Kenshin: Meiji Kenkaku Romantan',
 'Stranger: Mukou Hadan',
 'Detective Conan Movie 06: The Phantom of Baker Street',
 'Fate/stay night: Unlimited Blade Works',
 'Major S1',
 'Mobile Suit Gundam: The Origin',
 'Nanatsu no Taizai',
 'Natsume Yuujinchou',
 'One Piece Film: Strong World',
 'Higurashi no Naku Koro ni Kai',
 'Hunter x Hunter OVA',
 'Hunter x Hunter: Greed Island Final',
 'Kuroshitsuji: Book of Murder',
 'Major S2',
 'One Outs',
 'Beck',
 'Berserk',
 'Cowboy Bebop: Tengoku no Tobira',
 'Major S3',
 'Mobile Suit Gundam Unicorn',
 'Natsume Yuujinchou: Itsuka Yuki no Hi ni',
 'NHK ni Youkoso!',
 'Rose of Versailles',
 'Sakurasou no Pet na Kanojo',
 'Angel Beats!',
 'Bakemonogatari',
 'Bungou Stray Dogs 2nd Season',
 'Hajime no Ippo: Champion Road',
 'One Piece Film: Z',
 'Ouran Koukou Host Club',
 'Detective Conan Movie 13: The Raven Chaser',
 'Durarara!!',
 'Nodame Cantabile Finale',
 'Planetes',
 'Shelter',
 'Tenkuu no Shiro Laputa',
 'Gintama: Shiroyasha Koutan',
 'Hachimitsu to Clover II',
 'InuYasha: Kanketsu-hen',
 'Kaguya-hime no Monogatari',
 'Katekyo Hitman Reborn!',
 'Kuroshitsuji: Book of Circus',
 'Ookami to Koushinryou',
 'Boku no Hero Academia',
 'Gin no Saji 2nd Season',
 'Little Busters!: Refrain',
 'Major: Message',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa 2',
 'SKET Dance',
 'Bakuman.',
 'Danshi Koukousei no Nichijou',
 'Kotonoha no Niwa',
 'Kyoukai no Kanata Movie: I&#039;ll Be Here - Mirai-hen',
 'Major S4',
 'Omoide no Marnie',
 'Working!!!: Lord of the Takanashi',
 'Ghost in the Shell',
 'K-On! Movie',
 'Kuroko no Basket: Saikou no Present Desu',
 'Mahou Shoujo Lyrical Nanoha: The Movie 2nd A&#039;s',
 'Sennen Joyuu',
 'Steins;Gate: Kyoukaimenjou no Missing Link - Divide By Zero',
 'xxxHOLiC Kei',
 'Berserk: Ougon Jidai-hen III - Kourin',
 'Death Parade',
 'Fullmetal Alchemist',
 'Gyakkyou Burai Kaiji: Ultimate Survivor',
 'Hunter x Hunter: Greed Island',
 'Redline',
 'Chihayafuru',
 'Detective Conan Movie 20: The Darkest Nightmare',
 'Dragon Ball Z',
 'Fate/stay night: Unlimited Blade Works - Prologue',
 'Kokoro ga Sakebitagatterunda.',
 'Mimi wo Sumaseba',
 'Nagi no Asukara',
 'Neon Genesis Evangelion',
 'One Piece Film: Gold',
 'Tokyo Godfathers',
 'Trigun',
 'xxxHOLiC Rou',
 'Gintama: Shinyaku Benizakura-hen',
 'Mahou Shoujo Madoka★Magica Movie 1: Hajimari no Monogatari',
 'Sekaiichi Hatsukoi 2',
 'Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku',
 'Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku OVA',
 'Aria The Natural',
 'Black Lagoon: The Second Barrage',
 'Clannad',
 'Kami nomi zo Shiru Sekai: Megami-hen',
 'Summer Wars',
 'Baccano! Specials',
 'Detective Conan Movie 14: The Lost Ship in the Sky',
 'Gyakkyou Burai Kaiji: Hakairoku-hen',
 'Initial D Final Stage',
 'Kaiba',
 'One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari',
 'Saiki Kusuo no Ψ-nan (TV)',
 'Cardcaptor Sakura Movie 2: Fuuin Sareta Card',
 'Hajime no Ippo: Mashiba vs. Kimura',
 'Kamisama Hajimemashita◎',
 'Skip Beat!',
 'Yowamushi Pedal: Grande Road',
 'Gankutsuou',
 'Majo no Takkyuubin',
 'Nodame Cantabile: Paris-hen',
 'One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna',
 'Osomatsu-san',
 'Space☆Dandy 2nd Season',
 'Tsumiki no Ie',
 'Detroit Metal City',
 'Eve no Jikan',
 'Eve no Jikan (Movie)',
 'Kaichou wa Maid-sama!',
 'Saint Seiya: Meiou Hades Juuni Kyuu-hen',
 'Zankyou no Terror',
 'Darker than Black: Kuro no Keiyakusha',
 'Detective Conan',
 'Detective Conan Movie 05: Countdown to Heaven',
 'Diamond no Ace',
 'Fairy Tail (2014)',
 'Hibike! Euphonium 2',
 'JoJo no Kimyou na Bouken: Stardust Crusaders',
 'Maison Ikkoku',
 'Non Non Biyori Repeat',
 'Shijou Saikyou no Deshi Kenichi',
 'Yuusha-Ou GaoGaiGar Final',
 'Gekkan Shoujo Nozaki-kun',
 'Initial D Fourth Stage',
 'Junjou Romantica 2',
 'Kaze Tachinu',
 'Kingdom',
 'Kuragehime',
 'Magi: The Labyrinth of Magic',
 'Mobile Suit Gundam 00',
 'ReLIFE',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa',
 'Seirei no Moribito',
 'Akatsuki no Yona',
 'Detective Conan Movie 08: Magician of the Silver Sky',
 'Durarara!!x2 Ketsu',
 'Free!: Eternal Summer Special',
 'Glass no Kamen (2005)',
 'Gosick',
 'Hajime no Ippo: Boxer no Kobushi',
 'Initial D First Stage',
 'Kill la Kill',
 'Lovely★Complex',
 'Perfect Blue',
 'Princess Tutu',
 'Sakasama no Patema',
 'Tsubasa: Shunraiki',
 'Ashita no Joe',
 'Fairy Tail',
 'Ghost in the Shell: Stand Alone Complex - Solid State Society',
 'Magi: Sinbad no Bouken (TV)',
 'Shoujo Kakumei Utena',
 'Tengen Toppa Gurren Lagann Movie: Gurren-hen',
 'Detective Conan Movie 10: Requiem of the Detectives',
 'Evangelion: 1.0 You Are (Not) Alone',
 'Full Metal Panic? Fumoffu',
 'Ginga Eiyuu Densetsu: Arata Naru Tatakai no Overture',
 'Kara no Kyoukai 3: Tsuukaku Zanryuu',
 'Mobile Suit Gundam 00 Second Season',
 'Nisemonogatari',
 'Tsukimonogatari',
 'Ansatsu Kyoushitsu (TV)',
 'Aria The Avvenire',
 'Baby Steps 2nd Season',
 'D.Gray-man',
 'Ginga Eiyuu Densetsu Gaiden: Senoku no Hoshi, Senoku no Hikari',
 'Gintama: Jump Festa 2014 Special',
 'Lupin III: Cagliostro no Shiro',
 'Mobile Suit Gundam: Iron-Blooded Orphans 2nd Season',
 'Ookiku Furikabutte: Natsu no Taikai-hen',
 'Saiunkoku Monogatari 2nd Season',
 'Sekaiichi Hatsukoi Movie: Yokozawa Takafumi no Baai',
 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai. Movie',
 'Dennou Coil',
 'Eureka Seven',
 'Ghost in the Shell: Stand Alone Complex - The Laughing Man',
 'Gintama: Dai Hanseikai',
 'Hidamari Sketch: Sae Hiro Sotsugyou-hen',
 'Hikaru no Go',
 'Kimi ni Todoke',
 'Kokoro Connect: Michi Random',
 'Tokyo Magnitude 8.0',
 'Cardcaptor Sakura',
 'ef: A Tale of Melodies.',
 'Gin no Saji',
 'Hachimitsu to Clover',
 'Kodomo no Omocha (TV)',
 'Love Live! The School Idol Movie',
 'Mahoutsukai no Yome: Hoshi Matsu Hito',
 'Sekaiichi Hatsukoi OVA',
 'Working!!!',
 'Black Lagoon',
 'Detective Conan Movie 18: The Sniper from Another Dimension',
 'Final Fantasy VII: Advent Children Complete',
 'Higurashi no Naku Koro ni',
 'Hyouka',
 'Interstella5555: The 5tory of The 5ecret 5tar 5ystem',
 'Kanon (2006)',
 'Kimi ni Todoke 2nd Season',
 'Noragami',
 'Persona 3 the Movie 4: Winter of Rebirth',
 'xxxHOLiC Shunmuki',
 'Zetsuen no Tempest',
 'Aria The Origination: Sono Choppiri Himitsu no Basho ni...',
 'Detective Conan Movie 03: The Last Wizard of the Century',
 'Detective Conan Movie 04: Captured in Her Eyes',
 'Dragon Ball',
 'Hanada Shounen-shi',
 'Junjou Romantica 3',
 'Juuni Kokuki',
 'Major Movie: Yuujou no Winning Shot',
 'Mirai Shounen Conan',
 'One Piece Film: Strong World Episode 0',
 'Phantom: Requiem for the Phantom',
 'Tamako Love Story',
 'Toaru Kagaku no Railgun S',
 'Touch',
 'Yowamushi Pedal',
 'Akira',
 'Black Lagoon: Roberta&#039;s Blood Trail',
 'Durarara!!x2 Shou',
 'Gintama: Jump Festa 2015 Special',
 'High☆Speed!: Free! Starting Days',
 'Kyou kara Ore wa!!',
 'Nurarihyon no Mago: Sennen Makyou',
 'Paprika',
 'Prince of Tennis: The National Tournament Finals',
 'School Rumble Ni Gakki',
 'Sekaiichi Hatsukoi',
 'Akagami no Shirayuki-hime 2nd Season',
 'Clannad: Mou Hitotsu no Sekai, Tomoyo-hen',
 'Ginga Nagareboshi Gin',
 'Initial D Fifth Stage',
 'K-On!!',
 'Log Horizon',
 'Sekaiichi Hatsukoi: Valentine-hen',
 'Slayers Next',
 'Aria The OVA: Arietta',
 'Detective Conan Movie 15: Quarter of Silence',
 'Digimon Adventure tri. 3: Kokuhaku',
 'Gintama: Nanigoto mo Saiyo ga Kanjin nano de Tasho Senobisuru Kurai ga Choudoyoi',
 'Igano Kabamaru',
 'Kamisama Hajimemashita',
 'Kara no Kyoukai: Mirai Fukuin',
 'Mobile Suit Gundam: The 08th MS Team',
 'Omae Umasou da na',
 'Ushio to Tora (TV) 2nd Season',
 'Wolf&#039;s Rain OVA',
 'Ajin 2nd Season',
 'Aoki Hagane no Arpeggio: Ars Nova Cadenza',
 'City Hunter 2',
 'Durarara!!x2 Ten',
 'ef: A Tale of Memories.',
 'Ghost in the Shell 2.0',
 'Ghost in the Shell: Stand Alone Complex 2nd GIG - Individual Eleven',
 'Ginga Sengoku Gunyuuden Rai',
 'Initial D Second Stage',
 'Kami nomi zo Shiru Sekai II',
 'Noragami Aragoto OVA',
 'Stand By Me Doraemon',
 'Tiger &amp; Bunny',
 'Yahari Ore no Seishun Love Comedy wa Machigatteiru.',
 'Fullmetal Alchemist: Brotherhood Specials',
 'Hanamonogatari',
 'Kimi to Boku. 2',
 'Ookiku Furikabutte',
 'Ore Monogatari!!',
 'Tamayura: Sotsugyou Shashin Part 4 - Ashita',
 'Tekkon Kinkreet',
 'There She Is!!',
 'xxxHOLiC',
 'Byousoku 5 Centimeter',
 'Danganronpa 3: The End of Kibougamine Gakuen - Kibou-hen',
 'Ginga Eiyuu Densetsu Gaiden: Rasen Meikyuu',
 'Hyouge Mono',
 'Karigurashi no Arrietty',
 'Mahou Shoujo Lyrical Nanoha A&#039;s',
 'Rurouni Kenshin: Meiji Kenkaku Romantan - Seisou-hen',
 'Tanaka-kun wa Itsumo Kedaruge',
 'Berserk: Ougon Jidai-hen II - Doldrey Kouryaku',
 'Darker than Black: Kuro no Keiyakusha Gaiden',
 'Elsword: El Lady',
 'Ginga Eiyuu Densetsu: Waga Yuku wa Hoshi no Taikai',
 'Hikaru no Go: Journey to the North Star Cup',
 'Hybrid Child',
 'Isekai no Seikishi Monogatari',
 'Junjou Romantica OVA',
 'Kobato.',
 'Kuuchuu Buranko',
 'Macross: Do You Remember Love?',
 'One Piece 3D2Y: Ace no shi wo Koete! Luffy Nakama Tono Chikai',
 'Prince of Tennis: The National Tournament',
 'Prince of Tennis: The National Tournament Semifinals',
 'Eyeshield 21',
 'Full Moon wo Sagashite',
 'Grisaia no Rakuen',
 'Jigoku Shoujo Futakomori',
 'Junjou Romantica',
 'Mawaru Penguindrum',
 'SKET Dance OVA',
 'Soul Eater',
 'Trigun: Badlands Rumble',
 'Haibane Renmei',
 'Kuroko no Basket: Tip Off',
 'Macross',
 'Mirai Nikki (TV)',
 'Saiyuuki Reload: Burial',
 'Tentai Senshi Sunred 2nd Season',
 'Terra e... (TV)',
 'Tokyo Ghoul',
 'Usagi Drop Specials',
 'Yume-iro Pâtissière',
 'Azumanga Daioh',
 'Colorful (Movie)',
 'Detective Conan OVA 09: The Stranger in 10 Years...',
 'Drifters: Special Edition',
 'FLCL',
 'Full Metal Panic! The Second Raid',
 'Kuroshitsuji',
 'Love Live! School Idol Project 2nd Season',
 'Macross F Movie 2: Sayonara no Tsubasa',
 'Magi: Sinbad no Bouken',
 'Nekomonogatari: Kuro',
 'Saiunkoku Monogatari',
 'School Rumble',
 'Strike the Blood II',
 'Suzumiya Haruhi no Yuuutsu',
 'Flanders no Inu (Movie)',
 'Golden Boy',
 'Grisaia no Meikyuu: Caprice no Mayu 0',
 'Kaleido Star',
 'Kara no Kyoukai 4: Garan no Dou',
 'Lupin III vs. Detective Conan: The Movie',
 'Non Non Biyori',
 'Seitokai Yakuindomo* OVA',
 'Yakitate!! Japan',
 'Beelzebub',
 'Death Billiards',
 'Durarara!! Specials',
 'Jormungand: Perfect Order',
 'Mahou Shoujo Lyrical Nanoha: The Movie 1st',
 'Overlord',
 'Prince of Tennis',
 'Takarajima',
 'xxxHOLiC Movie: Manatsu no Yoru no Yume',
 'Yuru Yuri San☆Hai!',
 'Boruto: Naruto the Movie',
 'Coquelicot-zaka kara',
 'Eikoku Koi Monogatari Emma: Molders-hen',
 'Ergo Proxy',
 'Hanasaku Iroha',
 'Hataraku Maou-sama!',
 'Hibike! Euphonium',
 'Higashi no Eden',
 'Ie Naki Ko Remi',
 'Kono Subarashii Sekai ni Shukufuku wo!',
 'Kurenai no Buta',
 'Mobile Suit Zeta Gundam',
 'Prison School',
 'Saint Seiya',
 'Sayonara Zetsubou Sensei',
 'Seto no Hanayome OVA',
 'Zoku Sayonara Zetsubou Sensei',
 'Akachan to Boku',
 'Clannad: After Story - Mou Hitotsu no Sekai, Kyou-hen',
 'Hakuouki Movie 2: Shikon Soukyuu',
 'Kara no Kyoukai 2: Satsujin Kousatsu (Zen)',
 'Macross F',
 'Magic Kaito',
 'Sakigake!! Cromartie Koukou',
 'Shijou Saikyou no Deshi Kenichi OVA',
 'Touhai Densetsu Akagi: Yami ni Maiorita Tensai',
 'Carnival Phantasm',
 'D.Gray-man Hallow',
 'Date A Live: Encore OVA',
 'Dragon Ball Kai (2014)',
 'Gochuumon wa Usagi Desu ka??',
 'Hidamari Sketch x ☆☆☆',
 'Kokoro Connect',
 'Saiyuuki Gaiden',
 'Shirokuma Cafe',
 'Tiger &amp; Bunny Movie 2: The Rising',
 'Zan Sayonara Zetsubou Sensei',
 'City Hunter',
 'Detective Conan Movie 02: The Fourteenth Target',
 'Gekkan Shoujo Nozaki-kun Specials',
 'Giant Robo the Animation: Chikyuu ga Seishi Suru Hi',
 'Hetalia: The Beautiful World Specials',
 'Kaleido Star: Legend of Phoenix - Layla Hamilton Monogatari',
 'Kamisama Hajimemashita OVA',
 'Little Witch Academia',
 'Maria-sama ga Miteru 3rd',
 'Mobile Suit Gundam Thunderbolt',
 'The Everlasting Guilty Crown',
 'Bishoujo Senshi Sailor Moon: Sailor Stars',
 'Break Blade 4: Sanka no Chi',
 'Hanasaku Iroha: Home Sweet Home',
 'Hidamari Sketch x Honeycomb',
 'Hokuto no Ken',
 'Les Misérables: Shoujo Cosette',
 'Serial Experiments Lain',
 'Shiki',
 'Ushiro no Shoumen Daare',
 'Baka to Test to Shoukanjuu Ni!',
 'Detective Conan Movie 01: The Timed Skyscraper',
 'Detective Conan Movie 07: Crossroad in the Ancient Capital',
 'Gundam Build Fighters',
 'Hetalia: The Beautiful World',
 'Initial D Third Stage',
 'Kuroko no Basket 3rd Season NG-shuu',
 'Neko no Ongaeshi',
 'Seihou Bukyou Outlaw Star',
 'White Album 2',
 'Working&#039;!!',
 'Gate: Jieitai Kanochi nite, Kaku Tatakaeri',
 'Gate: Jieitai Kanochi nite, Kaku Tatakaeri 2nd Season',
 'Ghost Hunt',
 'Gungrave',
 'Jungle wa Itsumo Hare nochi Guu',
 'Kuroko no Basket 2nd Season NG-shuu',
 'Kyou kara Maou! 3rd Series',
 'Lupin III (2015)',
 'Madang-Eul Naon Amtalg',
 'Maria-sama ga Miteru 4th',
 'Musekinin Kanchou Tylor',
 'Ookami to Koushinryou II: Ookami to Kohakuiro no Yuuutsu',
 'Saint Seiya: Meiou Hades Meikai-hen',
 'Saint☆Oniisan (Movie)',
 'Seikai no Senki II',
 'Top wo Nerae! Gunbuster',
 'Toshokan Sensou: Kakumei no Tsubasa',
 'Uchouten Kazoku',
 'Baby Steps',
 'Break Blade 5: Shisen no Hate',
 'Code Geass: Hangyaku no Lelouch R2 Special Edition Zero Requiem',
 'Goku Sayonara Zetsubou Sensei',
 'Jormungand',
 'Kindaichi Shounen no Jikenbo (TV)',
 'Mobile Suit Gundam: Iron-Blooded Orphans',
 'Shin Mazinger Shougeki! Z-hen',
 'Tentai Senshi Sunred',
 'Yuusha-Ou GaoGaiGar',
 'Bleach',
 'Chuunibyou demo Koi ga Shitai!',
 'City Hunter 3',
 'Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen',
 'Detective Conan Movie 08: Time Travel of the Silver Sky',
 'Detective Conan OVA 10: Kid in Trap Island',
 'Dragon Ball Kai',
 'Hetalia World Series',
 'Jungle wa Itsumo Hare nochi Guu Deluxe',
 'Kami nomi zo Shiru Sekai',
 'Kyousou Giga (TV)',
 'Magic Kaito 1412',
 'Nejimaki Seirei Senki: Tenkyou no Alderamin',
 'Plastic Memories',
 'Psycho-Pass Movie',
 'Seto no Hanayome',
 'Sidonia no Kishi: Daikyuu Wakusei Seneki',
 'Tanoshii Muumin Ikka',
 'Tasogare Otome x Amnesia',
 'Vampire Hunter D (2000)',
 'Yuru Yuri Nachuyachumi!',
 'Break Blade 3: Kyoujin no Ato',
 'Danshi Koukousei no Nichijou Specials',
 'Detective Conan Movie 09: Strategy Above the Depths',
 'Detective Conan Movie 12: Full Score of Fear',
 'Final Fantasy VII: Advent Children',
 'Free!: Eternal Summer',
 'Hakuouki Movie 1: Kyoto Ranbu',
 'Hidamari Sketch x ☆☆☆ Specials',
 'K: Missing Kings',
 'Last Exile',
 'Little Busters!: EX',
 'Mobile Suit Gundam Wing: Endless Waltz Movie',
 'Naruto: Shippuuden',
 'Pokemon: The Origin',
 'Yuru Yuri♪♪',
 'Zan Sayonara Zetsubou Sensei Bangaichi',
 '3-gatsu no Lion',
 '91 Days',
 'Akagami no Shirayuki-hime',
 'Drifters',
 'Gake no Ue no Ponyo',
 'Ghost in the Shell 2: Innocence',
 'Haikyuu!! Movie 1: Owari to Hajimari',
 'Haikyuu!! OVA',
 'Hoozuki no Reitetsu OVA',
 'Keroro Gunsou',
 'Lupin III: Part II',
 'Macross F Movie 1: Itsuwari no Utahime',
 'Mobile Suit Gundam Seed',
 'Nodame Cantabile Finale Special',
 'Paradise Kiss',
 'Saint Seiya: The Hades Chapter Sanctuary - Yomigaerishi Gold Saint-tachi no Shinwa',
 'Saraiya Goyou',
 'Shiki Specials',
 'Slayers Try',
 'To LOVE-Ru Darkness 2nd Specials',
 'Transformers the Movie',
 'Uchuu Senkan Yamato 2199: Hoshimeguru Hakobune',
 'Wolf&#039;s Rain',
 'Akatsuki no Yona OVA',
 'Ao no Exorcist',
 'Claymore',
 'Detective Conan: Episode One - Chiisaku Natta Meitantei',
 'Ghost in the Shell: Stand Alone Complex - Solid State Society 3D',
 'Golden Time',
 'Hadashi no Gen',
 'Hayate no Gotoku!!',
 'Jinrui wa Suitai Shimashita',
 'Kyoukai no Kanata Movie: I&#039;ll Be Here - Kako-hen - Yakusoku no Kizuna',
 'Little Witch Academia: Mahoujikake no Parade',
 'Lucky☆Star: Original na Visual to Animation',
 'New Initial D Movie: Legend 1 - Kakusei',
 'Pandora Hearts',
 'Rurouni Kenshin DVD-BOX Special Ending',
 'Berserk: Ougon Jidai-hen I - Haou no Tamago',
 'Capeta',
 'Charlotte',
 'City Hunter &#039;91',
 'Kino no Tabi: Nanika wo Suru Tame ni - Life Goes On.',
 'Lupin the IIIrd: Jigen Daisuke no Bohyou',
 'Master Keaton OVA',
 'Mobile Suit Gundam Thunderbolt: December Sky',
 'Nisekoi',
 'Pokemon XY&amp;Z',
 'To LOVE-Ru Darkness 2nd OVA',
 'Yamada-kun to 7-nin no Majo (TV)',
 'Aoi Bungaku Series',
 'Arashi no Yoru ni',
 'Bokura wa Minna Kawaisou',
 'Chi&#039;s Sweet Home: Atarashii Ouchi',
 'Densetsu Kyojin Ideon: Hatsudou-hen',
 'Ginga Tetsudou 999',
 'Hana yori Dango',
 'Hanasakeru Seishounen',
 'Hidamari Sketch x 365',
 'Hidamari Sketch x SP',
 'Ie Naki Ko',
 'Michiko to Hatchin',
 'New Initial D Movie: Legend 2 - Tousou',
 'Persona 3 the Movie 2: Midsummer Knight&#039;s Dream',
 'Sexy Commando Gaiden: Sugoiyo!! Masaru-san',
 'Tegamibachi Reverse',
 'Ao Haru Ride',
 'Bishoujo Senshi Sailor Moon S',
 'Digimon Adventure',
 'Furiko',
 'Heartcatch Precure!',
 'InuYasha',
 'InuYasha: Kuroi Tessaiga',
 'InuYasha: Tenka Hadou no Ken',
 'K-On!!: Keikaku!',
 'Kumo no Mukou, Yakusoku no Basho',
 'Lupin III vs. Detective Conan',
 'Mobile Suit Gundam',
 'Mobile Suit Gundam III: Encounters in Space',
 'Noragami OVA',
 'Seitokai Yakuindomo OVA',
 'Urusei Yatsura Movie 2: Beautiful Dreamer',
 'Yamato Nadeshiko Shichihenge♥',
 'Another',
 'Ansatsu Kyoushitsu (TV) 2nd Season: Kagaijugyou-hen',
 'Ao no Exorcist Movie',
 'Arslan Senki (TV)',
 'Binbougami ga!',
 'Black Jack',
 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka',
 'Durarara!!x2 Shou: Watashi no Kokoro wa Nabe Moyou',
 'Hetalia World Series Specials',
 'K-On!: Live House!',
 'Kyou kara Maou!',
 'Kyoukai no Kanata',
 'Mind Game',
 'Oniisama e...',
 'Servamp Specials',
 'Shingeki no Kyojin OVA',
 'Tamayura: Sotsugyou Shashin Part 3 - Akogare',
 'The Last: Naruto the Movie',
 'The Law of Ueki',
 'Code Geass: Boukoku no Akito 2 - Hikisakareshi Yokuryuu',
 'Danganronpa 3: The End of Kibougamine Gakuen - Mirai-hen',
 'Hai to Gensou no Grimgar',
 'High School DxD New',
 'Huyao Xiao Hongniang: Yue Hong',
 'Jin-Rou',
 'K-On!',
 'Kino no Tabi: The Beautiful World - Byouki no Kuni - For You',
 'Lucky☆Star',
 'Mobile Suit Gundam Wing',
 'Mobile Suit Gundam Wing: Endless Waltz',
 'Piano no Mori',
 'Ranma ½',
 'Ranma ½ OVA',
 'Sidonia no Kishi',
 'Slayers',
 'Sora no Otoshimono: Tokeijikake no Angeloid',
 'Soukou Kihei Votoms',
 'Tantei Gakuen Q',
 'Toaru Kagaku no Railgun',
 'Uchuu Kaizoku Captain Harlock',
 'Watashi no Ashinaga Ojisan',
 'Break Blade 2: Ketsubetsu no Michi',
 'Chibi Maruko-chan',
 'Detective Conan Movie 16: The Eleventh Striker',
 'Genshiken 2',
 'Giovanni no Shima',
 'Hellsing I: Digest for Freaks',
 'Kuroko no Basket: Mou Ikkai Yarimasen ka',
 'Macross F: Close Encounter - Deculture Edition',
 'Non Non Biyori Repeat OVA',
 'Nurarihyon no Mago OVA',
 'One Piece: Episode of Luffy - Hand Island no Bouken',
 'One Punch Man Specials',
 'Seikai no Senki',
 'Sora no Otoshimono: Forte',
 'Space☆Dandy',
 'Arakawa Under the Bridge x Bridge',
 'Detective Conan Movie 10: Promo Special',
 'Elfen Lied',
 'Hachimitsu to Clover Specials',
 'Hello! Lady Lynn',
 'Kami nomi zo Shiru Sekai: Tenri-hen',
 'Kimi to Boku.',
 'Mahou Sensei Negima! Mou Hitotsu no Sekai',
 'Maria-sama ga Miteru: Haru',
 'Mobile Suit Gundam 0080: War in the Pocket',
 'Mondaiji-tachi ga Isekai kara Kuru Sou Desu yo?',
 'Nanatsu no Taizai OVA',
 'One Punch Man: Road to Hero',
 'Romeo x Juliet',
 'School Rumble Ichi Gakki Hoshuu',
 'Tamayura: Sotsugyou Shashin Part 2 - Hibiki',
 'Ajin Part 1: Shoudou',
 'Akame ga Kill!',
 'AKB0048: Next Stage',
 'Change!! Getter Robo: Sekai Saigo no Hi',
 'Death Note Rewrite',
 'Detective Conan Movie 17: Private Eye in the Distant Sea',
 'Hakuouki Sekkaroku',
 'Hoozuki no Reitetsu',
 'Kuroko no Basket NG-shuu',
 'Memories',
 'Naruto: Shippuuden Movie 6 - Road to Ninja',
 'Owari no Seraph: Nagoya Kessen-hen',
 'Seikai no Senki III',
 'Seitokai Yakuindomo*',
 'Space Cobra',
 'Toaru Majutsu no Index II',
 'Tsuritama',
 'Yowamushi Pedal Movie',
 'Yuru Yuri Nachuyachumi!+',
 'Baka to Test to Shoukanjuu',
 'Chi&#039;s Sweet Home',
 'Densetsu no Yuusha no Densetsu',
 'Fairy Tail OVA',
 'Ichigo Mashimaro OVA',
 'Kingsglaive: Final Fantasy XV',
 'Mobile Police Patlabor 2: The Movie',
 'Persona 3 the Movie 1: Spring of Birth',
 'Rozen Maiden: Ouvertüre',
 'Seikai no Monshou',
 'Shaman King',
 'Sword Art Online',
 'Tetsuwan Birdy Decode:02',
 'Bishoujo Senshi Sailor Moon Crystal Season III',
 'Bokurano',
 'Bounen no Xamdou',
 'Break Blade 6: Doukoku no Toride',
 'Detective Conan: Conan vs. Kid - Shark &amp; Jewel',
 'Dragon Ball Z Special 2: Zetsubou e no Hankou!! Nokosareta Chousenshi - Gohan to Trunks',
 'Hakkenden: Touhou Hakken Ibun 2nd Season',
 'Hidamari Sketch x 365 Specials',
 'K: Return of Kings',
 'Kill la Kill Special',
 'Kochira Katsushikaku Kameari Kouenmae Hashutsujo (TV)',
 'Macross Plus',
 'Macross Plus Movie Edition',
 'Mitsudomoe Zouryouchuu!',
 'Prince of Tennis: Another Story - Messages From Past and Future',
 'Saint Seiya: Meiou Hades Elysion-hen',
 'To LOVE-Ru Darkness',
 'To LOVE-Ru Darkness OVA',
 'Working!!',
 'Yume-iro Pâtissière SP Professional',
 'Daa! Daa! Daa!',
 'Digimon Adventure: Bokura no War Game!',
 'Eikoku Koi Monogatari Emma',
 'Full Metal Panic!',
 'Guilty Crown',
 'Hoshi wo Ou Kodomo',
 'Ima, Soko ni Iru Boku',
 'Jigoku Shoujo Mitsuganae',
 'Kara no Kyoukai 1: Fukan Fuukei',
 'Kimagure Orange☆Road: Ano Hi ni Kaeritai',
 'Kono Subarashii Sekai ni Shukufuku wo! OVA',
 'Kubikiri Cycle: Aoiro Savant to Zaregototsukai',
 'Lupin the Third: Mine Fujiko to Iu Onna',
 'Minami-ke',
 'Mobile Suit Gundam: Char&#039;s Counterattack',
 'Naruto',
 'New Game!',
 'Shigatsu wa Kimi no Uso: Moments',
 'Top wo Nerae 2! Diebuster',
 'Baka to Test to Shoukanjuu: Matsuri',
 'Blood+',
 'Chrno Crusade',
 'Free!: FrFr - Short Movie',
 'Fruits Basket',
 'Gakuen Alice',
 'Haikyuu!! Movie 2: Shousha to Haisha',
 'Hourou Musuko',
 'Huyao Xiao Hongniang: Wangquan Fugui',
 'Shoukoujo Sara',
 'Soredemo Sekai wa Utsukushii',
 'Tenkuu no Escaflowne',
 'The Disappearance of Conan Edogawa: The Worst Two Days in History',
 'To LOVE-Ru Darkness 2nd',
 'Tokyo Ravens',
 'Aikatsu! Movie',
 'Angel Beats! Specials',
 'Aria The Animation',
 'Break Blade 1: Kakusei no Toki',
 'Crayon Shin-chan Movie 09: Arashi wo Yobu Mouretsu! Otona Teikoku no Gyakushuu',
 'Denpa-teki na Kanojo',
 'Dragon Quest: Dai no Daibouken',
 'Higashi no Eden Soushuuhen: Air Communication',
 'Ichigo Mashimaro Encore',
 'Inu x Boku SS Special',
 'Jigoku Shoujo',
 'New Initial D Movie: Legend 3 - Mugen',
 'Nobunaga Concerto',
 'Panty &amp; Stocking with Garterbelt',
 'Poyopoyo Kansatsu Nikki',
 'Pretty Rhythm: Rainbow Live',
 'Ranma ½ Super',
 'Servant x Service',
 'Shakugan no Shana II (Second)',
 'Tales of Vesperia: The First Strike',
 'Toaru Hikuushi e no Tsuioku',
 'Towa no Quon 6: Towa no Quon',
 'Ajin',
 'Akagami no Shirayuki-hime: Nandemonai Takaramono, Kono Page',
 'Bishoujo Senshi Sailor Moon R: The Movie',
 'Code Geass: Hangyaku no Lelouch Special Edition Black Rebellion',
 'Full Metal Panic! The Second Raid: Wari to Hima na Sentaichou no Ichinichi',
 'Ga-Rei: Zero',
 'Higashi no Eden Movie II: Paradise Lost',
 'Jungle wa Itsumo Hare nochi Guu Final',
 'Kore wa Zombie Desu ka? of the Dead',
 'Kyoukai no Kanata: Shinonome',
 'Lupin III: Episode 0 &quot;First Contact&quot;',
 'Minami-ke Tadaima',
 'Momo e no Tegami',
 'Nurarihyon no Mago',
 'One Piece: Episode of Sabo - 3 Kyoudai no Kizuna Kiseki no Saikai to Uketsugareru Ishi',
 'Orange',
 'Over Drive',
 'R.O.D OVA',
 'Rakudai Kishi no Cavalry',
 'Ranma ½ Specials',
 'Rozen Maiden: Träumend',
 'Slam Dunk: Hoero Basketman-damashii! Hanamichi to Rukawa no Atsuki Natsu',
 'Special A',
 'Tenchi Muyou! Ryououki 2nd Season',
 'Texhnolyze',
 'Urusei Yatsura',
 'Utawarerumono',
 'Air Gear: Kuro no Hane to Nemuri no Mori - Break on the Sky',
 'Black Jack 21',
 'Digimon Adventure tri. 2: Ketsui',
 'Fushigi Yuugi',
 'Ichigo Mashimaro',
 'JoJo no Kimyou na Bouken: Phantom Blood',
 'Koyomimonogatari',
 'Mobile Suit Gundam 00 Special Edition',
 'Ojamajo Doremi Na-i-sho',
 'One Piece Movie 6: Omatsuri Danshaku to Himitsu no Shima',
 'Sengoku Basara Movie: The Last Party',
 'Shingeki no Bahamut: Genesis',
 'Tenchi Muyou! Ryououki',
 'Tonari no Kaibutsu-kun',
 'Zero no Tsukaima F',
 'Ao Haru Ride OVA',
 'Bishoujo Senshi Sailor Moon S: Kaguya Hime no Koibito',
 'Bokura wa Minna Kawaisou: Hajimete no',
 'Bungou Stray Dogs',
 'Detective Conan Movie 19: The Hellfire Sunflowers',
 'Doraemon (1979)',
 'Genshiken',
 'Ginga Tetsudou 999 (Movie)',
 'Girls und Panzer: Kore ga Hontou no Anzio-sen Desu!',
 'Hakuouki Hekketsuroku',
 'Hetalia Axis Powers',
 'Itazura na Kiss',
 'Lupin III',
 'Mahouka Koukou no Rettousei',
 'Majin Tantei Nougami Neuro',
 'Master Keaton',
 'No.6',
 'One Piece Movie 4: Dead End no Bouken',
 'Senjou no Valkyria',
 'Tegamibachi',
 'Towa no Quon 4: Guren no Shoushin',
 'Turn A Gundam',
 'Bleach Movie 4: Jigoku-hen',
 'D-Frag!',
 'Detective Conan Movie 09: Promo Special',
 'Dragon Ball Z Special 1: Tatta Hitori no Saishuu Kessen',
 'Go! Princess Precure',
 'Hayate no Gotoku!',
 'InuYasha: Kagami no Naka no Mugenjo',
 'Kanojo to Kanojo no Neko: Everything Flows',
 'Kara no Kyoukai Remix: Gate of Seventh Heaven',
 'Kino no Tabi: The Beautiful World - Tou no Kuni',
 'Kono Danshi, Ningyo Hiroimashita.',
 'Kuroko no Basket: Baka ja Katenai no yo!',
 'Kyoukai no Kanata Movie: I&#039;ll Be Here - Kako-hen',
 'Mahoujin Guru Guru',
 'One Piece: Heart of Gold',
 'Shingeki no Kyojin Movie 2: Jiyuu no Tsubasa',
 'The iDOLM@STER',
 'Trapp Ikka Monogatari',
 'Utawarerumono Specials',
 'World Trigger',
 'Yuusha-Ou GaoGaiGar Final Grand Glorious Gathering',
 'Bishoujo Senshi Sailor Moon R',
 'Black Jack (TV)',
 'Cardcaptor Sakura Movie 1',
 'Detective Conan: Black History',
 'Fullmetal Alchemist: The Conqueror of Shamballa',
 'Genshiken OVA',
 'Hal',
 'Heartcatch Precure! Movie: Hana no Miyako de Fashion Show... Desu ka!?',
 'Higashi no Eden Movie I: The King of Eden',
 'Hungry Heart: Wild Striker',
 'Initial D Battle Stage 2',
 'Kekkai Sensen',
 'Love Stage!! OVA',
 'Mahou Shoujo Lyrical Nanoha StrikerS',
 'Mousou Dairinin',
 'Muumindani no Suisei',
 'Noein: Mou Hitori no Kimi e',
 'Persona 3 the Movie 3: Falling Down',
 'Sengoku Basara Two',
 'Shakugan no Shana',
 'Soukyuu no Fafner: Dead Aggressor - Exodus 2nd Season',
 'Taiyou no Ko Esteban',
 'Toriko',
 'UN-GO: Inga-ron',
 'Crayon Shin-chan',
 'Diamond no Ace OVA',
 'Doraemon Movie 31: Shin Nobita to Tetsujin Heidan - Habatake Tenshi-tachi',
 'Flip Flappers',
 'GetBackers',
 'K',
 'Katekyo Hitman Reborn! Special',
 'Kekkaishi',
 'Kuroshitsuji II Specials',
 ]

# Dropdown menu for anime title selection
anime_title = st.selectbox("Select an anime title:", allowed_titles)

# Slider to select number of recommendations
num_recommendations = st.slider("Number of recommendations:", min_value=1, max_value=20, value=10)

# Recommend button
if st.button("Recommend"):
    if anime_title:
        recommended_anime = recommend_anime(anime_title, num_recommendations)
        st.subheader(f"Anime similar to {anime_title}:")
        for anime in recommended_anime:
            st.write(anime)
    else:
        st.write("Please select an anime title.")

